os: linux
dist: xenial
language: java
jdk: openjdk11

addons:
  firefox: "83.0"

git:
  depth: false
  quiet: true

services:
  - xvfb
  - docker

import:
  - Alfresco/alfresco-process-tools:.travis.kubernetes_install.yml@master
  - Alfresco/alfresco-process-tools:.travis.helm_install.yml@master

cache:
  directories:
    - $HOME/.m2
# the cache can grow constantly
before_cache:
  - rm -rf $HOME/.m2/repository/org/alfresco/alfresco-share*
  - rm -rf $HOME/.m2/repository/org/alfresco/share*
  - rm -rf $HOME/.m2/repository/org/alfresco/alfresco-content-services-share-*
  - rm -rf $HOME/.m2/repository/org/alfresco/alfresco-wcmqs*

branches:
  only:
    - master
    - develop
    - /^SP\/.+$/
    - /.*\/APPS-.*$/

env:
  global:
    - REPO_TAG_NAME=7.0.0-A16
    - SHARE_TAG_NAME=latest
    # Release version has to start with real version (7.0.0-....) for the docker image to build successfully.
    - RELEASE_VERSION=7.0.0-A14
    - DEVELOPMENT_VERSION=7.0.0-SNAPSHOT
    - HOSTED_ZONE=dev.alfresco.me
    - KEEP_ENV=false

stages:
  - build
  - deploy
  - wait
  - tests
  - tearDown
  - release
  - company_release

before_install:
  - |
    pip install --upgrade awscli
    curl -o aws-iam-authenticator https://amazon-eks.s3.us-west-2.amazonaws.com/1.16.8/2020-04-16/bin/linux/amd64/aws-iam-authenticator
    curl -o aws-iam-authenticator.sha256 https://amazon-eks.s3.us-west-2.amazonaws.com/1.16.8/2020-04-16/bin/linux/amd64/aws-iam-authenticator.sha256
    openssl sha1 -sha256 aws-iam-authenticator
    chmod +x ./aws-iam-authenticator
    mkdir -p $HOME/bin && cp ./aws-iam-authenticator $HOME/bin/aws-iam-authenticator && export PATH=$PATH:$HOME/bin
    export PATH=$PATH:$HOME/bin
    aws eks update-kubeconfig --name appsTeam --region=eu-west-1

jobs:
  include:
    - name: "Build and Test"
      stage: build
      before_install: bash _ci/init.sh
      script: bash _ci/build.sh

    - name: "White Source"
      stage: build
      # only on SP branches or master and if it is not a PR
      if: fork = false AND (branch = develop OR branch =~ /support\/SP\/.*/ OR branch =~ /.*\/APPS-.*$/) AND type != pull_request
      before_install: bash _ci/init.sh
      script: travis_wait 30 bash _ci/whitesource.sh _ci/.wss-unified-agent.config

    - name: "Source Clear Scan (SCA)"
      stage: build
      # only on SP branches or master and if it is not a PR
      if: fork = false AND (branch = develop OR branch =~ /support\/SP\/.*/ OR branch =~ /.*\/APPS-.*$/) AND type != pull_request
      before_install: bash _ci/init.sh
      # Run Veracode
      install: skip
      script: travis_wait 30 bash _ci/source_clear.sh

    - name: "Deploy on K8s"
      stage: deploy
      install: skip
      script: bash _ci/deploy_k8s.sh

    - &test-staging
      name: "Admin Tools Tests"
      stage: tests
      jdk: openjdk11
      if: fork=false AND commit_message !~ /\[trigger company release|skip tests\]/
      before_install: bash _ci/init.sh
      install: skip
      script:
        - bash _ci/execute_share_web.sh "admin-tools-tests.xml"
      addons:
        artifacts:
            paths:
              - alfresco-tas-share-test/target/surefire-reports
              - alfresco-tas-share-test/target/reports
            target_paths: $TRAVIS_BUILD_NUMBER

    - <<: *test-staging
      name: "User and Authentication Tests"
      script: bash _ci/execute_share_web.sh "user-tests.xml"

    - <<: *test-staging
      name: "Content Tests"
      script: bash _ci/execute_share_web.sh "content-tests.xml"

    - name: "Delete environment"
      stage: tearDown
      install: skip
      script: bash _ci/delete-env.sh

    - name: "Release"
      stage: release
      if: fork=false AND commit_message =~ /\[release\]/ AND branch =~ /(master|develop|SP\/.+|HF\/.+)$/
      before_install: bash _ci/init_tag.sh
      script: travis_wait 30 _ci/maven_release.sh

    - name: "Company Release"
      stage: company_release
      if: fork=false AND commit_message =~ /\[trigger company release\]/ AND branch =~ /(master|SP\/.+|HF\/.+)$/
      before_install: bash _ci/init_tag.sh
      script: travis_wait 30 _ci/company-release.sh

notifications:
  slack:
    rooms:
      - secure: "ihTZTpK0hbk8jPPjTK7K92gqxV/hYYUMQaNmgTPUEUbQ86BcOMphGGt55AEb2pMUIiuGHLPwOAdwd7H5dKMeAAkXeE44VYp+kvcEKi7MtRrN74qsrlaOr2WopcDXfZHgLo+NiCjKFjcZ40Uye4sGu8Zo3tuEWmgCNWr0d253Pa3KkHBJG1qFW/W9J1A8bwxAyr9S1Ytyv/iqH2OCAX020lHAd+6rs2ZNiKx2NxtT8qk87VJZjc0IEpnkl2ZQZN+AVfb3bY88b6prkywSpJofJuMCOLadfg+GaGugOjC/WVrHh2FfrmtC1dBhKSIGgqskzDHo3yqIp3dXmpwv71EwdEOxnhV16h92MTRxilWQctck+UVfoDFjM1cV0ANpO4OMiKA8sGJmFn+tyLRgwYtarKdyJkp8993eEUnmweDppdI5BPfCU+HC8QYC4Fakym+u0Wv6dZneIPFIBP36UQNODoTX0m4DYl5VXmohwxjjdV5SpAWdUoAahrM1qn3WThEgrh8lG746J9I/M8VYq7ZHFOYphG9B40seLey0BWMBbwOblBC09xCHplHxoWsNvGyhxQnDq9TAd1+zXnrzNcApXgE2m0dy7+x8nkRYFzxkMyJVOh/wxolVvL/V5LyeJic54F1veuhJe74H0GkdsIhpGYwnjuinXHYd39xMorurdfU="
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_pull_requests: false
    template:
      - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository_slug}@%{branch} by %{author} %{result} in %{duration}"